language: php
php:
- '7.0'
- '5.6'
env:
  - PACKAGE_NAME="thunderstorm_${TRAVIS_TAG}.zip"
install: 
  - composer install
  - touch database/database.sqlite
  - cp .env.example .env
  - php artisan migrate
  - perl -p -i -e 's/APP_ENV=local/APP_ENV=production/g' .env # Turn the environment to production
  - perl -p -i -e 's/APP_DEBUG=true/APP_DEBUG=false/g' .env # Turn the debug mode off
script: zip -q -r ${PACKAGE_NAME} .
deploy:
  skip_cleanup: true
  provider: releases
  file: $PACKAGE_NAME
  api_key:
    $GITHUB_TOKEN
  on:
    tags: true
    repo: padarom/thunderstorm
notifications:
  email: false
